# Turns a binary file (OptiX PTX) into a C++ translation unit so the renderer
# stays a single self contained executable.
#
# Usage: cmake -DINPUT=<file> -DOUTPUT=<file.cpp> -DSYMBOL=<name> -P embed_binary.cmake
#
# Do not run string(REGEX REPLACE) on the whole hex dump. CMake's regex is
# quadratic in the input length; a multi-megabyte shade_surface PTX hangs
# Windows CI for tens of minutes (the "Compile OptiX PTX" 45 min timeout).
# Convert a few hundred bytes at a time instead.

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
    message(FATAL_ERROR "embed_binary.cmake requires INPUT, OUTPUT and SYMBOL")
endif()

if(NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "embed_binary.cmake: INPUT does not exist: ${INPUT}")
endif()

file(SIZE "${INPUT}" BYTE_COUNT)

file(WRITE "${OUTPUT}"
"// Generated by embed_binary.cmake - do not edit.
extern \"C\" const unsigned char ${SYMBOL}[] = {
")

# 256 bytes = 16 rows of 16 values. Regex stays on a few hundred chars.
set(_chunk_bytes 256)
set(_offset 0)

while(_offset LESS BYTE_COUNT)
    file(READ "${INPUT}" _hex HEX OFFSET ${_offset} LIMIT ${_chunk_bytes})
    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1," _bytes "${_hex}")
    # CMake regex has no {16} quantifier; wrap with a fixed 16-byte pattern.
    string(REGEX REPLACE
        "(0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],)"
        "\\1\n    " _bytes "${_bytes}")
    file(APPEND "${OUTPUT}" "    ${_bytes}\n")
    math(EXPR _offset "${_offset} + ${_chunk_bytes}")
endwhile()

file(APPEND "${OUTPUT}"
"    0x00
};
extern \"C\" const unsigned long long ${SYMBOL}Size = ${BYTE_COUNT}ull;
")

message(STATUS "embed ${SYMBOL}: ${BYTE_COUNT} bytes -> ${OUTPUT}")
