# Turns a binary file (OptiX PTX) into a C++ translation unit so the renderer
# stays a single self contained executable.
#
# Usage: cmake -DINPUT=<file> -DOUTPUT=<file.cpp> -DSYMBOL=<name> -P embed_binary.cmake

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
    message(FATAL_ERROR "embed_binary.cmake requires INPUT, OUTPUT and SYMBOL")
endif()

file(READ "${INPUT}" CONTENT HEX)
string(LENGTH "${CONTENT}" HEX_LENGTH)
math(EXPR BYTE_COUNT "${HEX_LENGTH} / 2")

# Convert "0a1b..." into "0x0a,0x1b,..." with line breaks every 16 bytes.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," BYTES "${CONTENT}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n    " BYTES "${BYTES}")

file(WRITE "${OUTPUT}"
"// Generated by embed_binary.cmake - do not edit.
extern \"C\" const unsigned char ${SYMBOL}[] = {
    ${BYTES}
    0x00
};
extern \"C\" const unsigned long long ${SYMBOL}Size = ${BYTE_COUNT}ull;
")
