#!/usr/bin/env python3
"""Emit a C++ translation unit that embeds a binary as a byte array.

CMake string(APPEND) / REGEX REPLACE on a multi-megabyte PTX dump is quadratic
and hung Windows CI. This path is linear in the file size.
"""
from __future__ import print_function

import sys
from pathlib import Path


def main(argv):
    if len(argv) != 4:
        print("usage: embed_binary.py INPUT OUTPUT SYMBOL", file=sys.stderr)
        return 2
    src, dst, symbol = argv[1], argv[2], argv[3]
    data = Path(src).read_bytes()
    hexdigits = b"0123456789abcdef"
    out = bytearray()
    out += b"// Generated by embed_binary.py - do not edit.\n"
    out += ('extern "C" const unsigned char %s[] = {\n' % symbol).encode("ascii")
    col = 0
    line = bytearray(b"    ")
    for byte in data:
        if col == 16:
            line += b"\n"
            out += line
            line = bytearray(b"    ")
            col = 0
        line += b"0x"
        line.append(hexdigits[byte >> 4])
        line.append(hexdigits[byte & 15])
        line += b","
        col += 1
    if col:
        line += b"\n"
        out += line
    out += b"    0x00\n};\n"
    out += (
        'extern "C" const unsigned long long %sSize = %dull;\n' % (symbol, len(data))
    ).encode("ascii")
    Path(dst).write_bytes(bytes(out))
    sys.stdout.write("-- embed %s: %d bytes -> %s\n" % (symbol, len(data), dst))
    sys.stdout.flush()
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
