# Turns a binary file (OptiX PTX) into a C++ translation unit so the renderer
# stays a single self contained executable.
#
# Usage: cmake -DINPUT=<file> -DOUTPUT=<file.cpp> -DSYMBOL=<name> -P embed_binary.cmake
#
# Do not run string(REGEX REPLACE) on the whole hex dump: CMake's regex is
# quadratic and a multi-megabyte shade_surface PTX hung Windows CI until the
# 45-minute "Compile OptiX PTX" cap. Also do not file(APPEND) once per tiny
# chunk — on Windows each append rewrites the growing .cpp and that is the
# next timeout. Convert a few kilobytes at a time into a CMake string, then
# write the translation unit once.

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
    message(FATAL_ERROR "embed_binary.cmake requires INPUT, OUTPUT and SYMBOL")
endif()

if(NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "embed_binary.cmake: INPUT does not exist: ${INPUT}")
endif()

file(SIZE "${INPUT}" BYTE_COUNT)

set(_body "")
# 4 KiB of input → ~20 KiB of "0xNN," text. Regex stays linear; ~1024 loops for 4 MiB.
set(_chunk_bytes 4096)
set(_offset 0)

while(_offset LESS BYTE_COUNT)
    file(READ "${INPUT}" _hex HEX OFFSET ${_offset} LIMIT ${_chunk_bytes})
    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1," _bytes "${_hex}")
    # CMake regex has no {16} quantifier; wrap with a fixed 16-byte pattern.
    string(REGEX REPLACE
        "(0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],0x[0-9a-fA-F][0-9a-fA-F],)"
        "\\1\n    " _bytes "${_bytes}")
    string(APPEND _body "    ${_bytes}\n")
    math(EXPR _offset "${_offset} + ${_chunk_bytes}")
endwhile()

file(WRITE "${OUTPUT}"
"// Generated by embed_binary.cmake - do not edit.
extern \"C\" const unsigned char ${SYMBOL}[] = {
${_body}    0x00
};
extern \"C\" const unsigned long long ${SYMBOL}Size = ${BYTE_COUNT}ull;
")

message(STATUS "embed ${SYMBOL}: ${BYTE_COUNT} bytes -> ${OUTPUT}")
